"use client";
import React from "react";

export default function TermsOfUse() {
  return (
    <div className="prose prose-blue max-w-4xl mx-auto p-8 bg-white rounded-lg shadow-md">
      <h1>Terms of Use for Legally</h1>
      <p><strong>Last Updated:</strong> May 2nd, 2025</p>

      <p>
        Welcome to <strong>Legally</strong>, a platform that provides AI-powered legal assistance for immigration and asylum matters. By accessing or using Legally, you agree to be bound by these Terms of Use. If you do not agree, please do not use the service.
      </p>

      <hr />

      <h2>1. Eligibility</h2>
      <ul>
        <li>Be at least 18 years old, or have parental/guardian consent</li>
        <li>Provide accurate registration information</li>
        <li>Use the service only for lawful purposes</li>
      </ul>

      <hr />

      <h2>2. Use of the Service</h2>
      <ul>
        <li>Ask legal questions and upload documents in good faith</li>
        <li>Not submit false, harmful, or illegal content</li>
        <li>Not use automated tools to extract or abuse responses</li>
        <li>Abide by local, national, and international laws</li>
      </ul>
      <p>You also acknowledge:</p>
      <ul>
        <li>The chatbot provides informational assistance, not legal representation</li>
        <li>You are solely responsible for your use of any advice or response generated</li>
      </ul>

      <hr />

      <h2>3. Accounts & Security</h2>
      <ul>
        <li>Maintain the confidentiality of your account and password</li>
        <li>Do not share your login credentials</li>
        <li>Notify us immediately of unauthorized access</li>
      </ul>
      <p>We reserve the right to suspend or terminate accounts that violate these Terms.</p>

      <hr />

      <h2>4. Uploaded Files</h2>
      <p>You retain ownership of files uploaded to Legally, but by uploading, you:</p>
      <ul>
        <li>Grant us permission to process them for context and legal interpretation</li>
        <li>Confirm you have the right to share those files</li>
        <li>Acknowledge that deleting your account removes associated files and data</li>
      </ul>

      <hr />

      <h2>5. Intellectual Property</h2>
      <ul>
        <li>All content, UI, code, and responses generated by the platform are owned by Legally or appropriately licensed</li>
        <li>You may not reproduce, distribute, or reverse-engineer any part of the service</li>
      </ul>

      <hr />

      <h2>6. Termination</h2>
      <p>We may suspend or terminate your access:</p>
      <ul>
        <li>If you breach any of these Terms</li>
        <li>For security or operational reasons</li>
        <li>At our sole discretion</li>
      </ul>
      <p>You may delete your account at any time.</p>

      <hr />

      <h2>7. Disclaimer of Warranties</h2>
      <p><strong>Legally</strong> is provided “as is” and “as available.” We do not warrant:</p>
      <ul>
        <li>That responses are legally comprehensive or error-free</li>
        <li>That the service will always be uninterrupted or secure</li>
      </ul>
      <p>Use of the platform does not constitute attorney-client privilege.</p>

      <hr />

      <h2>8. Limitation of Liability</h2>
      <ul>
        <li>We are not liable for indirect, incidental, or consequential damages</li>
        <li>We are not liable for decisions or actions taken based on generated responses</li>
      </ul>
      <p>You use the service at your own risk.</p>

      <hr />

      <h2>9. Modifications</h2>
      <p>We may update these Terms at any time. Continued use of the service after updates constitutes acceptance.</p>

      <hr />

      <h2>10. Contact</h2>
      <p>
        For questions or requests, either use the contact form or email us at:{" "}
        <a href="mailto:long131005@gmail.com" className="text-blue-600 underline">
          long131005@gmail.com
        </a>
      </p>
    </div>
  );
}